# Generated by Django 3.2.8 on 2021-11-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
